name: Regular base image update check
on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:

  check:
    runs-on: ubuntu-latest
    outputs:
      needs-updating: ${{ steps.check.outputs.needs-updating }}
    steps:

      - name: Login to DockerHub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Image Update Checker
        id: check
        uses: lucacome/docker-image-update-checker@v2.0.0
        with:
          base-image: nextcloud:fpm-alpine
          image: zalf/fairagro-nextcloud:latest

  build:
    needs: check
    if: needs.check.outputs.needs-updating == 'true'
    runs-on: ubuntu-latest
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.9.0
        with:
          context: "${{ github.workspace }}"
          push: true
          tags: zalf/fairagro-nextcloud:latest
        if: steps.baseupdatecheck.outputs.needs-updating == 'true'