name: Docker Build latest

# Although we only want to push docker images to docker hub on pushes to main (that result from
# pull requests), we also subscribe to the pull request event itself. In this case we won't upload
# the image, but still build it so we are noticed if it fails.
on:
  # A successful merge request to main will result into a push to main.
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  schedule:
    - cron: "0 2 * * *"
  # For manual triggering
  workflow_dispatch:

jobs:
  nextcloud_version:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.nextcloud.outputs.tag }}
    steps:
      - name: Get nextcloud version
        id: nextcloud
        shell: bash
        run: |
          tag=$(curl -L --fail "https://hub.docker.com/v2/repositories/library/nextcloud/tags/?page_size=1000" | \
            jq '.results | .[] | .name' -r | \
            sed -n '/[0-9]\+.[0-9]\+.[0-9]\+-fpm-alpine/p' | \
            sort --version-sort | \
            tail -n 1)
          echo "::notice tag=$tag"
          echo "tag=$tag" >> $GITHUB_OUTPUT

  docker_build_call:
    permissions:
      contents: write # needed as git tags are created
    needs:
      - nextcloud_version
    name: call workflow docker-build
    uses: ./.github/workflows/docker-build.yml
    with:
      nextcloud_version: ${{ needs.nextcloud_version.outputs.tag }}
    secrets: inherit
